---
# file: roles/rabbitmq/tasks/limits.yml
- file: path=/etc/systemd/system/rabbitmq-server.service.d state=directory

- name: Increase file descriptor limit via Systemd
  template: src=etc/systemd/system/rabbitmq-server.service.d/limits.conf
    dest=/etc/systemd/system/rabbitmq-server.service.d/limits.conf
    owner=root
    group=root
    mode=0644
  notify: systemctl reload
  tags: rabbitmq-limits
